### PR TITLE
Cleanup and simplify ubuntu-22.04-fw-16.md tutorial

### PR DESCRIPTION
**Pull request by linux4life798**
The intention is to simplify and correct the presentation of this tutorial, in an effort to make it easier to follow.
I did not necessarily attempt to correct or alter the commands themselves. It should be noted that
there are still commands and steps that seem slightly off, but as written, they don't appear to be entirely
harmful.

The tutorial formatting is still far from perfect, but I feel that it is slightly easier to follow for normal and
power users. Additionally, it should should be slightly easier to manage using normal markdown editing
conventions.

### CODE REVIEW

**Comment by ctsdownloads** [comment]
Appreciate your efforts with this. I will take a gander asap to see if this is still merge friendly due to ongoing tweaks being made to the guide.

**Comment by JBBailly** [comment]
I followed the version of @linux4life798 for my FrameWork16 installation. It's easier to follow for beginners , and to read for more advanced users. Thank you !
I also compared to current vesion and didn't find any  error or typo.

**Comment by JBBailly** [comment]
Also, I think it would be better to redirect to step-2 of ubuntu-22.04-fw-16.md file in  the dialog box. For now it redirects to 22.04-OEM-D.md file.
(or copy @linux4life798 formatting to this file too)

**Comment by ctsdownloads** [comment]
Appreciate the feedback, will be redoing these manually in another format in the near future, so will skip this for now.

**Pull request closed without merging**
