### PR TITLE
FW13 easyeffects convolver fix

### PR DESCRIPTION
**Pull request by partofthething**
Bring in required Convolver impact file for FW13 easyeffects.

This irs file is required for the convolver plugin to work,
which creates the most significant change on the sound quality
of all the other settings. Without this file, the convolver plugin
errors out with 'Failed to load Impact file' and does not work.
With this file, the sound sounds great!

File sourced from https://github.com/cab404/framework-dsp/tree/master/config/irs

### CODE REVIEW

**Comment by ctsdownloads** [comment]
Interesting, can you provide additional details how this works, where it's placed and where it's needed? For Fedora and Ubuntu, the script as it is works flawlessly, so I wonder what the config different happens to be?

**Comment by partofthething** [comment]
For me, the script 'worked' at first on Ubuntu and sounded much better. But when I clicked on "effects" and then "convolver" it said "Failed to load Impact file" so I looked into it and figured this out. After loading the file, the convolver setting looks MUCH different, and the sound became, if you can believe it, EVEN BETTER!

Check your convolver setting and see if it looks like this. I'm guessing not if you don't have this file.  

image

**Comment by partofthething** [comment]
Anything else I can add to explain/demonstrate the impact of this more?

**Comment by ctsdownloads** [comment]
I'll see about reproducing this here but no the coming weeks.

**Comment by ctsdownloads** [comment]
Merged, appreciate the contribution.

**Pull request merged**
